### ISSUE TITLE
Attempt to read property "nama" on null

### ISSUE THREAD

**Issue by AkhyarAzamta** [AsepSahrudin18/e-desa-upgrade#5]
#**Error di app / Models / Kematian.php : 31**

![image](https://github.com/AsepSahrudin18/e-desa-upgrade/assets/45706780/8d3c2fe3-c094-4242-8fe4-1ba955c38acc?s=300)

#**Error di app / Models / Kelahiran.php : 31**

![image](https://github.com/AsepSahrudin18/e-desa-upgrade/assets/45706780/de8b0565-6fbe-4b34-b1da-c0c47fb8507b)

**Comment by AsepSahrudin18** [comment]
lah masih puh?
ini yang dari server apa di local puh?

**Comment by AkhyarAzamta** [comment]
done puh ternyata belum di seed
php artisan migrate:fresh --seed
